### ISSUE TITLE
Update express-stormpath to current version 

### ISSUE THREAD

**Issue by edjiang** [stormpath/express-stormpath-sample-project#14]
Maybe the package.json file should have a less specific specifier?

**Comment by robertjd** [comment]
For clarity I've changed package.json to use `^3.x` as the value for the express-stormpath dependency.  In practice, though, `^3.x` and `^3.0.0` have the same meaning.  You can test them out here: https://semver.npmjs.com/

**Comment by edjiang** [comment]
Oh ok, cool. I installed it on our demo machine today and it loaded 3.0.0 for some reason... Not sure why =]

Thanks!

**Comment by robertjd** [comment]
I'd make sure that the demo machine has an up-to-date version of NPM, older versions had bugs with semver processing.

**Comment by edjiang** [comment]
Gotcha, makes sense, thanks!
