### ISSUE TITLE
Some pages (Login, Registration) does not include NavBar

### ISSUE THREAD

**Issue by tomers** [stormpath/express-stormpath-sample-project#15]
It would be much more consistent to have all StormPath provided pages, such as Login, Registration, Forgot Password, etc., displayed with the NavBar header on top. It would improve the over-all consistency and navigability of the application.

Could you guide me on how to achieve this, or fix this in the sample app?

Thanks

**Comment by robertjd** [comment]
Hi @tomers , thanks for the question.  Please feel free to fork and modify this sample application to fit your needs, see this section of the express-stormpath documentation:

https://docs.stormpath.com/nodejs/express/latest/templates.html

That section describes how to provide custom templates, by copying and modifying ours.  When you modify them you could include a common navbar.

Let me know if this helps?
