### ISSUE TITLE
Custom Data is Not Saved on Profile Page

### ISSUE THREAD

**Issue by rdegges** [stormpath/express-stormpath-sample-project#6]
As the title says, the profile page of this example application is not currently functional:

![custom-data-bug](https://cloud.githubusercontent.com/assets/90247/12569636/818fa686-c385-11e5-9f59-c319355bfc00.gif)

**Comment by robertjd** [comment]
This is now fixed on master.  This example was relying on the fact that `express-stormpath` was attaching a form parser to all routes, but we took that out in 2.3.5 - so now that has to be configured outside our library.
